defmodule ExScreen.SSD1306.CommandFlags do
  defstruct set_contrast: 0x81,
            display_all_on_resume: 0xA4,
            display_all_on: 0xA5,
            normal_display: 0xA6,
            invert_display: 0xA7,
            display_off: 0xAE,
            display_on: 0xAF,
            set_display_offset: 0xD3,
            set_com_pins: 0xDA,
            set_vcom_detect: 0xDB,
            set_display_clock_div: 0xD5,
            set_pre_charge: 0xD9,
            set_multiplex: 0xA8,
            set_low_column: 0x00,
            set_high_column: 0x10,
            set_start_line: 0x40,
            set_memory_mode: 0x20,
            set_column_address: 0x21,
            set_page_address: 0x22,
            com_scan_inc: 0xC0,
            com_scan_dec: 0xC8,
            set_seg_remap: 0xA0,
            set_charge_pump: 0x8D,
            activate_scroll: 0x2F,
            deactivate_scroll: 0x2E,
            set_vertical_scroll_area: 0xA3,
            right_horizontal_scroll: 0x26,
            left_horizontal_scroll: 0x27,
            vertical_and_right_horizontal_scroll: 0x29,
            vertical_and_left_horizontal_scroll: 0x2A
end

